name: BiliTools

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  FORK_REPOSITORY: 'zhijieFork/BiliTools'
  UPSTREAM_REPOSITORY: 'https://github.com/btjawa/BiliTools.git'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.FORK_REPOSITORY }}
          ref: 'main'
          token: ${{ secrets.PAT }}

      - name: Configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with upstream
        run: |
          git remote add upstream ${{ env.UPSTREAM_REPOSITORY }} || true
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
